### ISSUE TITLE
NotImplementedError: there could be this many dbs, but I don't support it yet

### ISSUE THREAD

**Issue by salty4n6** [lxndrblz/forensicsim#17] opened 2023-07-17 21:38 UTC
Traceback (most recent call last):
  File "C:\Personal\Git\forensicsim\utils\main.py", line 314, in <module>
    cli()
  File "C:\Personal\Git\forensicsim\utils\main.py", line 309, in cli
    run(args)
  File "C:\Personal\Git\forensicsim\utils\main.py", line 292, in run
    process_db(args.filepath, args.outputpath)
  File "C:\Personal\Git\forensicsim\utils\main.py", line 282, in process_db
    extracted_values = shared.parse_db(filepath)
  File "C:\Personal\Git\forensicsim\utils\shared.py", line 170, in parse_db
    db = FastIndexedDB(filepath)
  File "C:\Personal\Git\forensicsim\utils\shared.py", line 53, in __init__
    self.fetch_data()
  File "C:\Personal\Git\forensicsim\utils\shared.py", line 78, in fetch_data
    raise NotImplementedError("there could be this many dbs, but I don't support it yet")
NotImplementedError: there could be this many dbs, but I don't support it yet

Also running into this problem.  Any ideas what's up?  Just curious is this on your roadmap to look at?

~Salty

**Comment by zoen101** [comment] 2023-08-11 23:38
Ran the ms_teams_parser with a similar result... I have 29 leveldb files and a total of 34 files there in total. Any thoughts on how to address this @lxndrblz?

Teams Version 3.3.2.0

Traceback (most recent call last):
  File "main.py", line 314, in <module>
  File "main.py", line 309, in cli
  File "main.py", line 292, in run
  File "main.py", line 282, in process_db
  File "shared.py", line 170, in parse_db
  File "shared.py", line 53, in __init__
  File "shared.py", line 78, in fetch_data
NotImplementedError: there could be this many dbs, but I don't support it yet
[19128] Failed to execute script 'main' due to unhandled exception!

**Comment by lxndrblz** [comment] 2023-08-26 08:06
Duplicate of #13

**Closed by lxndrblz** 2023-08-26 08:06 UTC
